"""Generate the Kaggle T4 benchmark notebook source.

The Kaggle MCP server only takes a notebook *body* -- there is no file upload and
no way to push a branch from this box.  So the notebook seeds itself from the
public GitHub tip (which is the BASE sha below) and then overlays the handful of
files this working tree has changed, carried inline as a gzip+base64 tar.

Usage::

    uv run python scratch_perf/kaggle/make_notebook.py --tag r2_baseline \
        --arm "base:nn_scene_UHD.py" --arm "base:nn_scene_PREVIEW.py"

Each ``--arm`` is ``<name>:<script>[:<ENV=v,ENV=v>]``; the script path is
relative to ``benchmarks/performance/``.  The notebook body lands in
``scratch_perf/kaggle/nb_<tag>.py``; paste it into ``save_notebook``'s ``text``.

**Always pass a modest ``sessionTimeoutSeconds``** (an hour is plenty for
these arms).  Kaggle allows two *batch* GPU sessions at a time and a queued
or wedged run holds one for its whole timeout; at the 9-hour default that is
a day of the measurement box gone, and there is no MCP tool that lists
sessions or cancels one by id.  Nothing notifies you when a run ends either,
so arm a timer and poll ``get_notebook_session_status`` yourself.
"""

from __future__ import annotations

import argparse
import base64
import gzip
import io
import os
import hashlib
import subprocess
import sys
import tarfile

REPO = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
# --repo overrides it: this box keeps several git worktrees of algan and the
# patch must be cut from whichever one is quiescent.
# github/master, the tip a fresh `git clone` of the public repo lands on.
DEFAULT_BASE = "df07859d4db1b32a3bbe6bf25f67c81ec53e518a"
PATCH_PATHS = ("algan", "benchmarks", "pyproject.toml")


def _git(*args: str) -> str:
    return subprocess.run(
        ["git", *args], cwd=REPO, capture_output=True, text=True, check=True
    ).stdout


def build_overlay(base: str, extra: list[str], paths=None) -> tuple[str, str, list[str]]:
    """Return (b64 patch, b64 tar of --extra files, list of changed paths).

    The patch is ``git diff --binary <base>`` -- base commit against this working
    tree, so committed and uncommitted edits to tracked files ride together.  It
    is orders of magnitude smaller than shipping whole files, which matters
    because the notebook body travels inline through the MCP call.  Untracked
    files are excluded by construction; name one with ``--extra`` to tar it in.
    """
    # Limited to what the notebook actually runs: the round keeps its briefs,
    # reports, captured logs and archived patches under scratch_perf/, and none
    # of that belongs in a payload that travels inline through a tool call.
    # -U1: the tracer instrumentation is mostly reindentation, so context lines are
    # a third of the payload. The base is an exact sha, so one line is enough for
    # `git apply` to land every hunk.
    patch = _git("diff", "--binary", "--unified=1", base, "--", *(paths or PATCH_PATHS))
    names = [
        line.split(" b/", 1)[-1] for line in patch.splitlines() if line.startswith("diff --git ")
    ]

    buf = io.BytesIO()
    with tarfile.open(fileobj=buf, mode="w") as tar:
        for path in extra:
            tar.add(os.path.join(REPO, path), arcname=path)
    extra_b64 = base64.b64encode(gzip.compress(buf.getvalue(), 9)).decode() if extra else ""

    patch_b64 = (
        base64.b64encode(gzip.compress(patch.encode("utf-8"), 9)).decode() if patch else ""
    )
    return patch_b64, extra_b64, names + list(extra)


def payload_key(patch_b64: str, extra_b64: str) -> str:
    """Content hash of the payload, so a re-run can name it instead of resending.

    The notebook stores every payload it decodes under this key in the persisted
    working directory; a later notebook that passes the same key with empty
    bodies gets the same files without the megabyte of base64 travelling through
    the tool call again.
    """
    h = hashlib.sha256()
    h.update(patch_b64.encode())
    h.update(b"|")
    h.update(extra_b64.encode())
    return h.hexdigest()[:16]


NOTEBOOK = '''\
# Algan T4 perf harness -- generated by scratch_perf/kaggle/make_notebook.py
# tag: {tag}
import base64, gzip, io, json, os, pathlib, shutil, subprocess, sys, tarfile, time

TAG       = {tag!r}
BASE_SHA  = {base!r}
ARMS      = {arms!r}
PATCH_B64 = "{patch}"
EXTRA_B64 = "{extra}"
PAYLOAD   = {key!r}
FROM_TAG  = {from_tag!r}
SNAPSHOT  = {snapshot!r}
BRANCH    = {branch!r}

WORK  = pathlib.Path("/kaggle/working")
REPO  = WORK / "algan_repo"
CACHE = WORK / "algan_cache"
OUT   = WORK / "out" / TAG
OUT.mkdir(parents=True, exist_ok=True)
LOG   = (OUT / "run.log").open("w")
T0 = time.time()


def say(msg):
    line = f"[{{time.time()-T0:7.1f}}s] {{msg}}"
    print(line, flush=True)
    LOG.write(line + "\\n"); LOG.flush()


def sh(cmd, cwd=None, check=True, env=None, tail=4000):
    say(f"$ {{cmd}}")
    t = time.time()
    r = subprocess.run(cmd, shell=True, cwd=cwd, env=env,
                       stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True)
    out = r.stdout or ""
    if len(out) > tail:
        out = out[:tail // 2] + f"\\n... [{{len(out)-tail}} chars elided] ...\\n" + out[-tail // 2:]
    print(out, flush=True); LOG.write(out + "\\n")
    say(f"  -> exit {{r.returncode}} in {{time.time()-t:.1f}}s")
    if check and r.returncode:
        LOG.flush()
        raise SystemExit(f"FAILED: {{cmd}}")
    return r


sh("nvidia-smi", check=False)

# ---------------------------------------------------------------- 1. system deps
sh("apt-get install -y -qq libpango1.0-dev libcairo2-dev pkg-config")

# ---------------------------------------------------------------- 2. repo
if not (REPO / ".git").exists():
    shutil.rmtree(REPO, ignore_errors=True)
    sh(f"git clone --depth 1 https://github.com/algorithmicsimplicity/algan.git {{REPO}}")
head = subprocess.run("git rev-parse HEAD", shell=True, cwd=REPO,
                      capture_output=True, text=True).stdout.strip()
say(f"clone HEAD = {{head}}  (expected base {{BASE_SHA}})")
if head != BASE_SHA:
    say("WARNING: clone tip is not the base this overlay was cut against")

# pristine base, then overlay
sh("git checkout -- . && git clean -qfd algan benchmarks scratch_perf tests", cwd=REPO, check=False)
if BRANCH:
    # The branch is pushed to the public repo, so no payload machinery is
    # needed: fetch its tip and detach onto it.
    sh(f"git fetch --depth 1 origin {{BRANCH}}", cwd=REPO)
    sh("git checkout -f FETCH_HEAD", cwd=REPO)
    head = subprocess.run("git rev-parse HEAD", shell=True, cwd=REPO,
                          capture_output=True, text=True).stdout.strip()
    say(f"checked out branch {{BRANCH}} @ {{head}}")
if FROM_TAG:
    # Start from the snapshot a previous run committed in this clone.
    sh(f"git checkout -f {{FROM_TAG}}", cwd=REPO)
if PATCH_B64:
    patch = gzip.decompress(base64.b64decode(PATCH_B64)).decode("utf-8")
    (WORK / "overlay.patch").write_text(patch, encoding="utf-8", newline="\\n")
    say(f"patch: {{len(patch)}} chars, "
        f"{{sum(1 for L in patch.splitlines() if L.startswith('diff --git '))}} files")
    sh(f"git apply --verbose --whitespace=nowarn {{WORK / 'overlay.patch'}}", cwd=REPO)
if EXTRA_B64:
    with tarfile.open(fileobj=io.BytesIO(gzip.decompress(base64.b64decode(EXTRA_B64)))) as tar:
        tar.extractall(REPO)
        say(f"extra files: {{tar.getnames()}}")
sh("git status --porcelain", cwd=REPO, check=False)
if SNAPSHOT:
    # Commit the overlaid tree inside the clone and tag it, so the next run can
    # start here instead of at the public tip.
    sh("git -c user.name=algan-perf -c user.email=perf@local add -A algan benchmarks tests",
       cwd=REPO, check=False)
    sh(f"git -c user.name=algan-perf -c user.email=perf@local commit -q -m {{SNAPSHOT}} "
       f"--allow-empty", cwd=REPO, check=False)
    sh(f"git tag -f {{SNAPSHOT}}", cwd=REPO, check=False)
    say(f"snapshotted the overlaid tree as tag {{SNAPSHOT}}")

# ---------------------------------------------------------------- 3. install
sh(f"pip install -q -e {{REPO}}")

# ------------------------------------------------------------- 3b. GPU guard
# Kaggle's generic "Gpu" machine shape can hand out a Tesla P100 (cuda
# capability 6.0), which this torch build REFUSES -- its supported range is
# (7.0)-(12.0). Algan's _auto_render_device then falls back to CPU and every
# arm renders on a couple of slow vCPUs while the session log still shows a
# GPU. That happened twice (tags memo1 and memo2, 2026-08-27): fourteen arms
# of CPU numbers collected under a notebook called "t4 perf".
#
# ASK ALGAN, NOT TORCH. torch.cuda.is_available() returns TRUE on that P100 --
# it reports the device and only refuses the arch later -- so the obvious
# probe passes and the guard sleeps through exactly the case it exists for
# (that is what memo2 proved). The render device Algan actually resolved is
# the only answer that means anything here.
# The answer rides behind a SENTINEL, not at the start of stdout: importing
# algan pulls in Taichi, which prints its own two-line banner to stdout
# ("[Taichi] version ...", "[Taichi] Starting on arch=..."). A startswith
# check therefore reads the banner and is False whatever the device is -- it
# aborted a genuine 2x Tesla T4 session (tag memo3 v19), and the P100 aborts
# before it were right by accident rather than by test.
probe = subprocess.run(
    [sys.executable, "-c",
     "import torch;"
     "ok = torch.cuda.is_available();"
     "cap = torch.cuda.get_device_capability(0) if ok else None;"
     "name = torch.cuda.get_device_name(0) if ok else 'none';"
     "from algan.settings._startup import _RENDER_DEVICE as D;"
     "print('ALGAN_RENDER_DEVICE=' + D.type);"
     "print(f'{{name}} cap={{cap}} torch_cuda_available={{ok}}')"],
    capture_output=True, text=True)
say(f"algan render-device probe: {{probe.stdout.strip()!r}} "
    f"{{probe.stderr.strip()[-600:]}}")
if "ALGAN_RENDER_DEVICE=cuda" not in probe.stdout:
    raise SystemExit(
        "ABORT: Algan resolved its render device to CPU, so every arm would "
        "measure the wrong machine (a P100 is the usual cause -- torch "
        "refuses sm_60). Re-save with machineShape='NvidiaTeslaT4' -- that "
        "exact string, per agent_guidance/claude_memory/kaggle-t4-"
        "measurement.md. An unrecognised value is silently dropped and "
        "Kaggle falls back to the generic 'Gpu' shape, which is how this "
        "run got here."
    )

# ---------------------------------------------------------------- 4. run arms
CACHE.mkdir(exist_ok=True)
# Resumable: an arm that already produced a result in a previous session of this
# tag is skipped, so a run cut short (or a queue that ate a slot) can be picked
# up by re-saving rather than redone from the top.
results_path = OUT / "results.json"
results = json.loads(results_path.read_text()) if results_path.exists() else {{}}
scenes = REPO / "benchmarks" / "performance"
for name, script, extra_env in ARMS:
    if results.get(name, {{}}).get("exit") == 0:
        say(f"=== ARM {{name}}: already done in an earlier session, skipping")
        continue
    say(f"=== ARM {{name}}: {{script}}  env={{extra_env}}")
    # The base clone ships committed report files with the same names; clear
    # them so the collection below cannot mistake one for this arm's output.
    for stale in scenes.glob("algan_profile_report*.txt"):
        stale.unlink()
    env = dict(os.environ)
    env["ALGAN_CACHE_DIR"] = str(CACHE)
    env["ALGAN_USE_DAEMON"] = "0"
    env["MPLBACKEND"] = "Agg"
    env.update(extra_env)
    t = time.time()
    r = sh(f"python {{script}}", cwd=str(scenes), env=env, check=False, tail=200000)
    results[name] = dict(seconds=round(time.time() - t, 2), exit=r.returncode)
    # collect whatever profile reports the run wrote
    for p in sorted(scenes.glob("algan_profile_report*.txt")):
        dest = OUT / f"{{name}}__{{p.name}}"
        shutil.copy(p, dest)
        p.unlink()
    vids = sorted((scenes / "algan_outputs").glob("*.mp4")) if (scenes / "algan_outputs").exists() else []
    for v in vids:
        import hashlib
        h = hashlib.sha256(v.read_bytes()).hexdigest()[:16]
        results[name].setdefault("videos", {{}})[v.name] = dict(sha=h, bytes=v.stat().st_size)
        v.unlink()
    # Written after every arm so a session that dies mid-run still leaves a
    # resumable record.
    results_path.write_text(json.dumps(results, indent=2))

results_path.write_text(json.dumps(results, indent=2))
say("RESULTS " + json.dumps(results))
say(f"cache size: {{sum(f.stat().st_size for f in CACHE.rglob('*') if f.is_file())/2**20:.1f}} MB")
LOG.close()
print(open(OUT / "results.json").read())
'''


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--tag", required=True)
    ap.add_argument("--repo", default=None, help="worktree to cut the patch from")
    ap.add_argument("--base", default=DEFAULT_BASE)
    ap.add_argument(
        "--arm",
        action="append",
        default=[],
        help="<name>:<script>[:<K=V,K=V>]  script relative to benchmarks/performance/",
    )
    ap.add_argument("--extra", action="append", default=[], help="extra file to ship")
    ap.add_argument("--paths", action="append", default=[],
                    help="restrict the patch to these paths (repeatable)")
    ap.add_argument("--branch", default=None,
                    help="fetch and check out this pushed branch instead of patching")
    ap.add_argument("--from-tag", default=None,
                    help="snapshot tag a previous run committed in the Kaggle clone")
    ap.add_argument("--snapshot", default=None,
                    help="tag to commit the overlaid tree as, for later --from-tag")
    ap.add_argument(
        "--reuse-payload",
        default=None,
        help="content key of a payload already stored on Kaggle; sends empty bodies",
    )
    args = ap.parse_args()
    if args.repo:
        global REPO
        REPO = os.path.abspath(args.repo)

    arms = []
    for spec in args.arm:
        parts = spec.split(":")
        name, script = parts[0], parts[1]
        env = {}
        if len(parts) > 2 and parts[2]:
            for kv in parts[2].split(","):
                k, _, v = kv.partition("=")
                env[k] = v
        arms.append((name, script, env))

    patch, extra_tar, names = build_overlay(args.base, args.extra, args.paths or None)
    if args.branch:
        # the pushed branch carries the tree; only --extra files ride inline
        patch, names = "", [f"(branch {args.branch})", *args.extra]
    key = payload_key(patch, extra_tar)
    if args.reuse_payload:
        key, patch, extra_tar = args.reuse_payload, "", ""
    body = NOTEBOOK.format(
        tag=args.tag, base=args.base, arms=arms, patch=patch, extra=extra_tar, key=key,
        from_tag=args.from_tag or "", snapshot=args.snapshot or "",
        branch=args.branch or "",
    )
    out = os.path.join(os.path.dirname(__file__), f"nb_{args.tag}.py")
    with open(out, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(body)
    print(f"wrote {out}  ({len(body)} chars; patch {len(patch)} + extra {len(extra_tar)} b64)")
    print(f"payload key: {key}")
    print(f"overlay touches {len(names)} paths:")
    for p in names:
        print("   ", p)
    return 0


if __name__ == "__main__":
    sys.exit(main())
