# Algan T4 perf harness -- generated by scratch_perf/kaggle/make_notebook.py
# tag: struct2
import base64, gzip, io, json, os, pathlib, shutil, subprocess, sys, tarfile, time

TAG       = 'struct2'
BASE_SHA  = 'df07859d4db1b32a3bbe6bf25f67c81ec53e518a'
ARMS      = [('nnP_on2', 'nn_scene_PREVIEW.py', {}), ('nnU_on2', 'nn_scene_UHD.py', {}), ('galP_on2', 'static_gallery_PREVIEW.py', {}), ('nnP_off2', 'nn_scene_PREVIEW.py', {'ALGAN_TEXTURE_TIME_FLAT': '0', 'ALGAN_TEXTURE_CONTENT_DEDUP': '0', 'ALGAN_TEXTURE_WINDOW_COLLAPSE': '0', 'ALGAN_MERGE_DEDUP_GEOMETRY': '0'}), ('nnU_off2', 'nn_scene_UHD.py', {'ALGAN_TEXTURE_TIME_FLAT': '0', 'ALGAN_TEXTURE_CONTENT_DEDUP': '0', 'ALGAN_TEXTURE_WINDOW_COLLAPSE': '0', 'ALGAN_MERGE_DEDUP_GEOMETRY': '0'}), ('galP_off2', 'static_gallery_PREVIEW.py', {'ALGAN_TEXTURE_TIME_FLAT': '0', 'ALGAN_TEXTURE_CONTENT_DEDUP': '0', 'ALGAN_TEXTURE_WINDOW_COLLAPSE': '0', 'ALGAN_MERGE_DEDUP_GEOMETRY': '0'})]
PATCH_B64 = ""
EXTRA_B64 = ""
PAYLOAD   = 'cbe5cfdf7c2118a9'
FROM_TAG  = ''
SNAPSHOT  = ''
BRANCH    = 'claude/structural-redesigns-perf-pmpkv3'

WORK  = pathlib.Path("/kaggle/working")
REPO  = WORK / "algan_repo"
CACHE = WORK / "algan_cache"
OUT   = WORK / "out" / TAG
OUT.mkdir(parents=True, exist_ok=True)
LOG   = (OUT / "run.log").open("w")
T0 = time.time()


def say(msg):
    line = f"[{time.time()-T0:7.1f}s] {msg}"
    print(line, flush=True)
    LOG.write(line + "\n"); LOG.flush()


def sh(cmd, cwd=None, check=True, env=None, tail=4000):
    say(f"$ {cmd}")
    t = time.time()
    r = subprocess.run(cmd, shell=True, cwd=cwd, env=env,
                       stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True)
    out = r.stdout or ""
    if len(out) > tail:
        out = out[:tail // 2] + f"\n... [{len(out)-tail} chars elided] ...\n" + out[-tail // 2:]
    print(out, flush=True); LOG.write(out + "\n")
    say(f"  -> exit {r.returncode} in {time.time()-t:.1f}s")
    if check and r.returncode:
        LOG.flush()
        raise SystemExit(f"FAILED: {cmd}")
    return r


sh("nvidia-smi", check=False)

# ---------------------------------------------------------------- 1. system deps
sh("apt-get install -y -qq libpango1.0-dev libcairo2-dev pkg-config")

# ---------------------------------------------------------------- 2. repo
if not (REPO / ".git").exists():
    shutil.rmtree(REPO, ignore_errors=True)
    sh(f"git clone --depth 1 https://github.com/algorithmicsimplicity/algan.git {REPO}")
head = subprocess.run("git rev-parse HEAD", shell=True, cwd=REPO,
                      capture_output=True, text=True).stdout.strip()
say(f"clone HEAD = {head}  (expected base {BASE_SHA})")
if head != BASE_SHA:
    say("WARNING: clone tip is not the base this overlay was cut against")

# pristine base, then overlay
sh("git checkout -- . && git clean -qfd algan benchmarks scratch_perf tests", cwd=REPO, check=False)
if BRANCH:
    # The branch is pushed to the public repo, so no payload machinery is
    # needed: fetch its tip and detach onto it.
    sh(f"git fetch --depth 1 origin {BRANCH}", cwd=REPO)
    sh("git checkout -f FETCH_HEAD", cwd=REPO)
    head = subprocess.run("git rev-parse HEAD", shell=True, cwd=REPO,
                          capture_output=True, text=True).stdout.strip()
    say(f"checked out branch {BRANCH} @ {head}")
if FROM_TAG:
    # Start from the snapshot a previous run committed in this clone.
    sh(f"git checkout -f {FROM_TAG}", cwd=REPO)
if PATCH_B64:
    patch = gzip.decompress(base64.b64decode(PATCH_B64)).decode("utf-8")
    (WORK / "overlay.patch").write_text(patch, encoding="utf-8", newline="\n")
    say(f"patch: {len(patch)} chars, "
        f"{sum(1 for L in patch.splitlines() if L.startswith('diff --git '))} files")
    sh(f"git apply --verbose --whitespace=nowarn {WORK / 'overlay.patch'}", cwd=REPO)
if EXTRA_B64:
    with tarfile.open(fileobj=io.BytesIO(gzip.decompress(base64.b64decode(EXTRA_B64)))) as tar:
        tar.extractall(REPO)
        say(f"extra files: {tar.getnames()}")
sh("git status --porcelain", cwd=REPO, check=False)
if SNAPSHOT:
    # Commit the overlaid tree inside the clone and tag it, so the next run can
    # start here instead of at the public tip.
    sh("git -c user.name=algan-perf -c user.email=perf@local add -A algan benchmarks tests",
       cwd=REPO, check=False)
    sh(f"git -c user.name=algan-perf -c user.email=perf@local commit -q -m {SNAPSHOT} "
       f"--allow-empty", cwd=REPO, check=False)
    sh(f"git tag -f {SNAPSHOT}", cwd=REPO, check=False)
    say(f"snapshotted the overlaid tree as tag {SNAPSHOT}")

# ---------------------------------------------------------------- 3. install
sh(f"pip install -q -e {REPO}")

# ---------------------------------------------------------------- 4. run arms
CACHE.mkdir(exist_ok=True)
# Resumable: an arm that already produced a result in a previous session of this
# tag is skipped, so a run cut short (or a queue that ate a slot) can be picked
# up by re-saving rather than redone from the top.
results_path = OUT / "results.json"
results = json.loads(results_path.read_text()) if results_path.exists() else {}
scenes = REPO / "benchmarks" / "performance"
for name, script, extra_env in ARMS:
    if results.get(name, {}).get("exit") == 0:
        say(f"=== ARM {name}: already done in an earlier session, skipping")
        continue
    say(f"=== ARM {name}: {script}  env={extra_env}")
    # The base clone ships committed report files with the same names; clear
    # them so the collection below cannot mistake one for this arm's output.
    for stale in scenes.glob("algan_profile_report*.txt"):
        stale.unlink()
    env = dict(os.environ)
    env["ALGAN_CACHE_DIR"] = str(CACHE)
    env["ALGAN_USE_DAEMON"] = "0"
    env["MPLBACKEND"] = "Agg"
    env.update(extra_env)
    t = time.time()
    r = sh(f"python {script}", cwd=str(scenes), env=env, check=False, tail=200000)
    results[name] = dict(seconds=round(time.time() - t, 2), exit=r.returncode)
    # collect whatever profile reports the run wrote
    for p in sorted(scenes.glob("algan_profile_report*.txt")):
        dest = OUT / f"{name}__{p.name}"
        shutil.copy(p, dest)
        p.unlink()
    vids = sorted((scenes / "algan_outputs").glob("*.mp4")) if (scenes / "algan_outputs").exists() else []
    for v in vids:
        import hashlib
        h = hashlib.sha256(v.read_bytes()).hexdigest()[:16]
        results[name].setdefault("videos", {})[v.name] = dict(sha=h, bytes=v.stat().st_size)
        v.unlink()
    # Written after every arm so a session that dies mid-run still leaves a
    # resumable record.
    results_path.write_text(json.dumps(results, indent=2))

results_path.write_text(json.dumps(results, indent=2))
say("RESULTS " + json.dumps(results))
say(f"cache size: {sum(f.stat().st_size for f in CACHE.rglob('*') if f.is_file())/2**20:.1f} MB")
LOG.close()
print(open(OUT / "results.json").read())
