"""Source of truth for the packed kernel ABI (no renderer imports).

Each kernel lists its original public argument order once. A string is an
ordinary argument; (name, arena dtype tag, rank) is an arena-bound array.
Run ``python scripts/generate_arena_bindings.py`` after editing this file.
Generated literal prologues, specs and parameter lists stay in the kernel
modules for compiler source inspection and have no runtime generation cost.
Kernel signatures keep their explanatory comments and are validated, not
rewritten. Changing an ordinary argument also requires changing its signature
and explicit launch sites; the ABI tests cover those independently.
"""

from __future__ import annotations

LAYOUTS = {
    "pt_shade": (
        "path_tracer_taichi.py",
        (
            "active",
            "num_active",
            "t_nodes",
            ("t_node_miss", "i32", 1),
            ("t_leaf_prim", "i32", 1),
            ("t_leaf_tspan", "i32", 1),
            "t_first_leaf",
            ("tri_pos", "f32", 3),
            ("tri_norm", "f32", 3),
            ("tri_extra", "f32", 3),
            ("tri_colors", "f32", 4),
            ("tri_uvs", "f32", 3),
            ("tri_tex_meta", "i32", 2),
            ("textures", "f32", 3),
            "num_colored_triangles",
            "b_nodes",
            ("b_node_miss", "i32", 1),
            ("b_leaf_prim", "i32", 1),
            ("b_leaf_tspan", "i32", 1),
            "b_first_leaf",
            ("circuit_meta", "f32", 3),
            ("circuit_colors", "f32", 4),
            ("circuit_border_colors", "f32", 4),
            ("edges_2d", "f32", 3),
            ("edge_accel", "i32", 1),
            ("tri_mat_id", "i32", 2),
            ("tri_mat", "f32", 3),
            ("light_pos", "f32", 3),
            ("light_col", "f32", 3),
            "num_lights",
            ("pixel_world_scale", "f32", 1),
            "layer_offset_triangles",
            ("cam_origin", "f32", 2),
            "refit",
            "has_tri",
            "has_bez",
            "shadows",
            "shadow_mode",
            "vis_lights",
            "auth_sampled",
            "frag_pipelines",
            "frag_scatters",
            "tri_pids",
            "seed_root",
            "sample_base",
            "tile_pixels",
            "rr_start",
            "firefly_clamp",
            "time_start",
            "width",
            "height",
            "ray_offset",
            "rs_ro",
            "rs_rd",
            "rs_sca",
            "rs_int",
            "rs_pix",
            "hit_f",
            "hit_i",
            "pt_thru",
            "pt_acc",
            "pt_stats",
            ("nee_cdf", "f32", 1),
            ("nee_ref", "i32", 2),
            ("nee_meta", "f32", 1),
            ("tri_emit_prob", "f32", 1),
            ("env_cdf", "f32", 2),
            ("tri_shell", "i32", 2),
            "pt_aov",
            ("tri_emit_entry", "i32", 1),
            ("lt_node_f", "f32", 3),
            ("lt_node_i", "i32", 3),
            ("lt_entry_leaf", "i32", 2),
            ("lt_frame", "i32", 1),
            ("nee_inf_cdf", "f32", 1),
            ("nee_inf_ref", "i32", 1),
            ("pt_glass_energy", "f32", 2),
        ),
    ),
    "raster_shadow_trace": (
        "raster_taichi.py",
        (
            "num_events",
            "event_pos",
            "event_snrm",
            "event_fnrm",
            "event_frame",
            "event_msk",
            "t_nodes",
            ("t_node_miss", "i32", 1),
            ("t_leaf_prim", "i32", 1),
            ("t_leaf_tspan", "i32", 1),
            "t_first_leaf",
            ("tri_pos", "f32", 3),
            ("tri_colors", "f32", 4),
            ("tri_uvs", "f32", 3),
            ("tri_tex_meta", "i32", 2),
            ("textures", "f32", 3),
            ("tri_extra", "f32", 3),
            "num_colored_triangles",
            "b_nodes",
            ("b_node_miss", "i32", 1),
            ("b_leaf_prim", "i32", 1),
            ("b_leaf_tspan", "i32", 1),
            "b_first_leaf",
            ("circuit_meta", "f32", 3),
            ("circuit_colors", "f32", 4),
            ("circuit_border_colors", "f32", 4),
            ("edges_2d", "f32", 3),
            ("edge_accel", "i32", 1),
            ("light_pos", "f32", 3),
            ("light_col", "f32", 3),
            "num_lights",
            ("pixel_world_scale", "f32", 1),
            "layer_offset_triangles",
            "refit",
            "has_tri",
            "has_bez",
            "event_dp",
            "event_toff",
            "sec_aa",
            "shadow_vis",
            "shadow_anyhit",
            ("tri_obj", "i32", 2),
            "event_src_prim",
            "eps_self",
            "eps_near",
            "shadow_identity",
            "shadow_term",
            "adaptive_taps",
        ),
    ),
    "sheet_resolve_shade": (
        "sheet_resolve_taichi.py",
        (
            "num_covered",
            ("sheet_offsets", "i32", 1),
            ("sheet_key", "i64", 1),
            ("sheet_ref", "i32", 1),
            ("sheet_ab", "f32", 2),
            ("sheet_cov", "f32", 1),
            ("sheet_msk", "i32", 1),
            ("sheet_cap", "f32", 1),
            ("tri_pos", "f32", 3),
            ("tri_norm", "f32", 3),
            ("tri_extra", "f32", 3),
            ("tri_colors", "f32", 4),
            ("tri_uvs", "f32", 3),
            ("tri_tex_meta", "i32", 2),
            ("textures", "f32", 3),
            "num_colored_triangles",
            ("col_row", "i32", 1),
            ("tri_mat_id", "i32", 2),
            ("tri_mat", "f32", 3),
            ("circuit_meta", "f32", 3),
            ("circuit_colors", "f32", 4),
            ("circuit_border_colors", "f32", 4),
            ("light_pos", "f32", 3),
            ("light_col", "f32", 3),
            "num_lights",
            "vis_lights",
            ("render_floats", "f32", 1),
            ("render_ints", "i32", 1),
            "frag_shading",
            "frag_pipelines",
            "tri_pids",
            "refraction",
            "ior_stack",
            "skip_unlit_normal",
            "has_bez",
            "sec_aa",
            "sec_min_energy",
            "glossy",
            "env_in_composite",
            "direct_spec",
            "mode",
            "shadow_term",
            "sided_cull",
            "memo",
            ("sheet_memo", "f32", 2),
            ("sheet_accept", "i32", 1),
            ("event_pos", "f32", 2),
            ("event_snrm", "f32", 2),
            ("event_fnrm", "f32", 2),
            ("event_frame", "i32", 1),
            ("event_msk", "i32", 1),
            ("event_dp", "f32", 2),
            ("event_toff", "f32", 2),
            ("sheet_event_id", "i32", 1),
            ("shadow_vis", "f32", 3),
            ("covered_idx", "i32", 1),
            "time_start",
            "width",
            "height",
            ("cam_origin", "f32", 2),
            ("screen_point", "f32", 2),
            ("pixel_basis_x", "f32", 2),
            ("pixel_basis_y", "f32", 2),
            ("gen_meta", "f32", 1),
            "rs_ro",
            "rs_rd",
            "rs_acc",
            "rs_sca",
            "rs_int",
            "rs_pix",
            "pix_accum",
            ("rs_alloc", "i32", 1),
            "dump",
            "dump_out",
        ),
    ),
    "wavefront_shade": (
        "wavefront_kernels_taichi.py",
        (
            "active",
            "num_active",
            "t_nodes",
            ("t_node_miss", "i32", 1),
            ("t_leaf_prim", "i32", 1),
            ("t_leaf_tspan", "i32", 1),
            "t_first_leaf",
            ("tri_pos", "f32", 3),
            ("tri_norm", "f32", 3),
            ("tri_extra", "f32", 3),
            ("tri_colors", "f32", 4),
            ("tri_uvs", "f32", 3),
            ("tri_tex_meta", "i32", 2),
            ("textures", "f32", 3),
            "num_colored_triangles",
            ("col_row", "i32", 1),
            "b_nodes",
            ("b_node_miss", "i32", 1),
            ("b_leaf_prim", "i32", 1),
            ("b_leaf_tspan", "i32", 1),
            "b_first_leaf",
            ("circuit_meta", "f32", 3),
            ("circuit_colors", "f32", 4),
            ("circuit_border_colors", "f32", 4),
            ("edges_2d", "f32", 3),
            ("edge_accel", "i32", 1),
            ("pixel_world_scale", "f32", 1),
            ("render_floats", "f32", 1),
            ("render_ints", "i32", 1),
            "frag_shading",
            "frag_pipelines",
            "frag_scatters",
            "tri_pids",
            "shadows",
            "refraction",
            "ior_stack",
            "refit",
            "has_tri",
            "has_bez",
            "deferred_shadows",
            "shadow_term",
            "sided_cull",
            "skip_unlit_normal",
            "direct_spec",
            "mem_trim",
            "opaque_closest",
            "first_iter",
            "compact",
            "weight_floor_exit",
            "vis_lights",
            ("tri_mat_id", "i32", 2),
            ("tri_mat", "f32", 3),
            ("light_pos", "f32", 3),
            ("light_col", "f32", 3),
            "num_lights",
            "time_start",
            "width",
            "height",
            "ray_offset",
            "rs_ro",
            "rs_rd",
            "rs_acc",
            "rs_sca",
            "rs_int",
            "hit_f",
            "hit_i",
            "rs_pix",
            "pix_accum",
            "rs_alloc",
            "rs_vis",
            ("cam_origin", "f32", 2),
        ),
    ),
    "wavefront_traverse_events": (
        "wavefront_kernels_taichi.py",
        (
            "active",
            "num_active",
            "t_nodes",
            ("t_node_miss", "i32", 1),
            ("t_leaf_prim", "i32", 1),
            ("t_leaf_tspan", "i32", 1),
            "t_first_leaf",
            ("tri_pos", "f32", 3),
            "b_nodes",
            ("b_node_miss", "i32", 1),
            ("b_leaf_prim", "i32", 1),
            ("b_leaf_tspan", "i32", 1),
            "b_first_leaf",
            ("circuit_meta", "f32", 3),
            ("edges_2d", "f32", 3),
            ("edge_accel", "i32", 1),
            "ot_nodes",
            ("ot_node_miss", "i32", 1),
            ("ot_leaf_prim", "i32", 1),
            ("ot_leaf_tspan", "i32", 1),
            "ot_first_leaf",
            "ob_nodes",
            ("ob_node_miss", "i32", 1),
            ("ob_leaf_prim", "i32", 1),
            ("ob_leaf_tspan", "i32", 1),
            "ob_first_leaf",
            ("pixel_world_scale", "f32", 1),
            "layer_offset_triangles",
            "refit",
            "has_tri",
            "has_bez",
            "opaque_closest",
            "opaque_prepass",
            "time_start",
            "width",
            "height",
            "ray_offset",
            "rs_ro",
            "rs_rd",
            "rs_sca",
            "rs_int",
            "hit_f",
            "hit_i",
            "rs_pix",
            "gen_first",
            ("cam_origin", "f32", 2),
            ("screen_point", "f32", 2),
            ("pixel_basis_x", "f32", 2),
            ("pixel_basis_y", "f32", 2),
            ("gen_meta", "f32", 1),
        ),
    ),
}
