r"""Generate the notebook body that runs a set of commands on a Kaggle T4.

The body this emits is a bootstrap and nothing else -- apt, clone, install,
then hand over to ``scripts/kaggle/runner.py`` in the clone. Keeping it that
thin is the point: the body is transmitted inline on every launch, so every
line in it is paid for repeatedly and reviewed never.

Usage::

    uv run python scripts/kaggle/make_notebook.py \\
        --tag t4-baseline \\
        --branch claude/algan-gpu-harnesses-lnnifd \\
        --step "uhd:python benchmarks/performance/nn_scene_UHD.py" \\
        --step "preview:python benchmarks/performance/nn_scene_PREVIEW.py" \\
        --env ALGAN_VIDEO_ENCODER=software \\
        --out /tmp/nb.py

Then pass the file's contents as ``save_notebook``'s ``text``. The generator
also prints, to stderr, the exact kernel configuration the save must use --
including ``machineShape: "NvidiaTeslaT4"``, which is the single most expensive
thing to get wrong (see ``agent_guidance/gpu_harnesses.md``).

BRANCH MUST BE PUSHED FIRST. The box gets the code by cloning GitHub; there is
no patch-payload path here and there should not be, because this repository is
public and pushing a branch is one command.
"""

from __future__ import annotations

import argparse
import json
import pprint
import sys

DEFAULT_REPO_URL = "https://github.com/algorithmicsimplicity/algan.git"

# The Kaggle image ships torch+CUDA and ffmpeg, but not the Pango/Cairo
# headers manim's text stack builds against. ~25 s.
APT_PACKAGES = "libpango1.0-dev libcairo2-dev pkg-config ffmpeg"

# Extras installed with the clone. ``pango`` is the reason the apt list above
# carries the Pango/Cairo headers: without ``manimpango``, `algan.Text` falls
# back to LaTeX's text mode, and the Kaggle image has no TeX -- so a benchmark
# scene with a `Text` in it dies on the box rather than on this machine. It
# builds manimpango from source (~1 min, and site-packages does not persist
# between sessions, so it is paid per run).
DEFAULT_EXTRAS = "pango"

TEMPLATE = """\
# algan Kaggle T4 harness -- GENERATED by scripts/kaggle/make_notebook.py
# tag: {tag}
# branch: {branch}
#
# This body only bootstraps. The run itself is scripts/kaggle/runner.py in the
# clone, so read that file (in the repository) to know what this does.
import json
import os
import subprocess
import sys

SPEC = {spec}

WORK = "/kaggle/working"
REPO = os.path.join(WORK, "algan")
os.environ["ALGAN_CACHE_DIR"] = os.path.join(WORK, "algan_cache")
os.environ["PYTHONUNBUFFERED"] = "1"


def sh(cmd, check=True):
    print("+ " + cmd, flush=True)
    rc = subprocess.run(cmd, shell=True).returncode
    if rc != 0 and check:
        raise SystemExit("command failed (rc=%d): %s" % (rc, cmd))
    return rc


sh("nvidia-smi", check=False)
sh("apt-get -qq update && apt-get -qq install -y {apt}")

if not os.path.isdir(os.path.join(REPO, ".git")):
    sh("git clone --filter=blob:none {repo_url} " + REPO)
# --force everywhere: /kaggle/working persists between runs of this notebook, so
# the clone is whatever the previous run left, including a dirty tree.
sh("git -C %s fetch --force origin {branch}" % REPO)
sh("git -C %s checkout --force FETCH_HEAD" % REPO)
sh("git -C %s clean -fdx" % REPO)
sh("git -C %s log --oneline -1" % REPO)

EXTRAS = "{extras}"
if EXTRAS:
    # Not `check=True`: an extra that fails to build should not cost the whole
    # session. The fallback is the plain install, and the printed rc says which
    # one the run got.
    if sh("pip install -q -e '%s[%s]'" % (REPO, EXTRAS), check=False) != 0:
        print("!! extras [%s] failed to install; falling back" % EXTRAS, flush=True)
        sh("pip install -q -e " + REPO)
else:
    sh("pip install -q -e " + REPO)

rc = subprocess.run(
    [sys.executable, os.path.join(REPO, "scripts", "kaggle", "runner.py"),
     "--spec", json.dumps(SPEC), "--work-dir", WORK]
).returncode
print("runner exit code: %d" % rc, flush=True)
if rc != 0:
    raise SystemExit(rc)
"""


def parse_step(raw: str) -> dict:
    """``name:command`` -> a step. The first colon separates them."""
    if ":" not in raw:
        raise argparse.ArgumentTypeError(f"--step wants 'name:command', got {raw!r}")
    name, command = raw.split(":", 1)
    name = name.strip()
    if not name or not command.strip():
        raise argparse.ArgumentTypeError(f"--step wants 'name:command', got {raw!r}")
    if any(c in name for c in "/\\ "):
        raise argparse.ArgumentTypeError(
            f"step name {name!r} becomes a filename; keep it to a simple token"
        )
    return {"name": name, "command": command.strip()}


def parse_env(raw: str) -> tuple[str, str]:
    if "=" not in raw:
        raise argparse.ArgumentTypeError(f"--env wants KEY=VALUE, got {raw!r}")
    key, value = raw.split("=", 1)
    return key.strip(), value


def build_spec(args: argparse.Namespace) -> dict:
    return {
        "tag": args.tag,
        "branch": args.branch,
        "repo_url": args.repo_url,
        "steps": args.step,
        "env": dict(args.env),
        "allow_cpu": args.allow_cpu,
        "force": args.force,
        "step_timeout_seconds": args.step_timeout,
    }


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    parser.add_argument("--tag", required=True, help="names the run and its output dir")
    parser.add_argument(
        "--branch", required=True, help="branch to clone; must be pushed"
    )
    parser.add_argument(
        "--step",
        action="append",
        type=parse_step,
        required=True,
        metavar="NAME:COMMAND",
        help="a command to run from the repository root; repeatable",
    )
    parser.add_argument(
        "--env",
        action="append",
        type=parse_env,
        default=[],
        metavar="KEY=VALUE",
        help="environment applied to every step; repeatable",
    )
    parser.add_argument("--repo-url", default=DEFAULT_REPO_URL)
    parser.add_argument(
        "--extras",
        default=DEFAULT_EXTRAS,
        help="comma-separated pip extras to install with the clone "
        f"(default {DEFAULT_EXTRAS!r}; pass '' for none)",
    )
    parser.add_argument(
        "--allow-cpu",
        action="store_true",
        help="do not abort when Algan resolves a non-CUDA device (rarely what you want)",
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="re-run steps that already succeeded in an earlier session of this tag",
    )
    parser.add_argument(
        "--step-timeout",
        type=float,
        default=None,
        help="kill any single step after this many seconds",
    )
    parser.add_argument("--out", default="-", help="write the body here ('-' = stdout)")
    parser.add_argument(
        "--session-timeout",
        type=int,
        default=3600,
        help="reported in the config block; Kaggle's sessionTimeoutSeconds",
    )
    args = parser.parse_args(argv)

    spec = build_spec(args)
    body = TEMPLATE.format(
        tag=args.tag,
        branch=args.branch,
        repo_url=args.repo_url,
        apt=APT_PACKAGES,
        extras=args.extras,
        # A PYTHON literal, not JSON: `null`/`true`/`false` would reach the
        # box as bare names and blow up after apt, clone and install have
        # already been paid for.
        spec=pprint.pformat(spec, indent=4, width=88, sort_dicts=True),
    )

    if args.out == "-":
        sys.stdout.write(body)
    else:
        with open(args.out, "w", encoding="utf-8") as handle:
            handle.write(body)

    slug = f"algan-{args.tag}"
    config = {
        "newTitle": slug,
        "enableGpu": True,
        "enableInternet": True,
        "machineShape": "NvidiaTeslaT4",
        "kernelType": "script",
        "language": "python",
        "kernelExecutionType": "SaveAndRunAll",
        "isPrivate": True,
        "sessionTimeoutSeconds": args.session_timeout,
    }
    print(f"# wrote {len(body)} chars to {args.out}", file=sys.stderr)
    print("# save_notebook request fields (text = the body above):", file=sys.stderr)
    print(json.dumps(config, indent=2), file=sys.stderr)
    print(
        "# machineShape MUST be exactly 'NvidiaTeslaT4' -- an unrecognised value is\n"
        "# dropped silently and Kaggle hands you a P100, on which Algan renders on\n"
        "# the CPU. runner.py aborts if that happens, but the save still costs a slot.",
        file=sys.stderr,
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
