"""The half of the Kaggle T4 harness that runs *on the box*.

The notebook body generated by ``make_notebook.py`` is a bootstrap and nothing
more: it clones this repository at the requested branch, installs it, and hands
control to this file. Everything that decides what a run *means* -- which
device it is allowed to run on, which commands it runs, what counts as a
result, what a resumed run skips -- lives here, in the repository, where it is
versioned and can be read without decoding a notebook.

That split is deliberate. A generated notebook body is the most expensive place
to put logic: it has to be transmitted inline on every launch, it is invisible
to code review, and changing it means regenerating and re-saving rather than
committing. The only cost of keeping the logic here instead is that the branch
must be pushed before the run is launched -- which it must be anyway, because
the clone is how the code reaches the box.

Run layout, all under ``/kaggle/working`` (which persists between runs of the
same notebook, and is what carries the clone and the Taichi kernel cache):

    out/<tag>/results.json   the machine-readable summary, and the resume state
    out/<tag>/<step>.log     one file per step, its full captured output
    algan/                   the clone
    algan_cache/             ALGAN_CACHE_DIR

Nothing here is Kaggle-specific except those paths, so ``--work-dir`` is enough
to run it on any box with a GPU.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import subprocess
import sys
import time
from pathlib import Path

# Printed verbatim as the last line of a successful run. `read_output.py` and
# any human reading the log grep for it, so it must stay a single line of JSON
# behind a fixed prefix.
RESULTS_PREFIX = "RESULTS "


def _log(message: str) -> None:
    print(message, flush=True)


def _banner(message: str) -> None:
    _log("")
    _log("=" * 78)
    _log(message)
    _log("=" * 78)


def check_render_device(repo: Path, allow_cpu: bool) -> str:
    """Abort unless Algan resolved a CUDA render device.

    This is the guard the T4 harness exists to have. A mis-typed
    ``machineShape`` does not fail the save -- Kaggle quietly satisfies the
    generic ``Gpu`` shape with whatever it has, often a Tesla P100, whose
    compute capability this torch build refuses; Algan then falls back to the
    CPU and every number in the run is a CPU number taken on a notebook titled
    "t4". Two rounds of measurements were collected that way before anyone
    noticed.

    The probe has to ask ALGAN, not torch: ``torch.cuda.is_available()``
    returns True on that P100 (it reports the device and only rejects the arch
    when a kernel is launched), so the obvious check sails straight through.
    ``algan.settings._startup.render_device()`` is the accessor of record --
    the render device is a runtime setting, so nothing else is authoritative.
    """
    probe = (
        "import algan, torch;"
        " from algan.settings import _startup;"
        " d = _startup.render_device();"
        " print('ALGAN_DEVICE %s' % d.type);"
        " print('TORCH %s cuda=%s' % (torch.__version__, torch.cuda.is_available()));"
        " print('GPU %s' % (torch.cuda.get_device_name(0) if torch.cuda.is_available() else 'none'))"
    )
    out = subprocess.run(
        [sys.executable, "-c", probe],
        cwd=repo,
        capture_output=True,
        text=True,
    )
    _log(out.stdout.rstrip())
    if out.stderr.strip():
        _log(out.stderr.rstrip())
    if out.returncode != 0:
        raise SystemExit(
            "the device probe failed to import algan; see the output above"
        )

    device = ""
    for line in out.stdout.splitlines():
        if line.startswith("ALGAN_DEVICE "):
            device = line.split(" ", 1)[1].strip()
    if device != "cuda" and not allow_cpu:
        raise SystemExit(
            f"Algan resolved render device {device!r}, not 'cuda'. This is almost "
            "always a wrong machineShape: it must be exactly 'NvidiaTeslaT4'. "
            "Refusing to take CPU numbers on a run labelled as a GPU run. Pass "
            "--allow-cpu (or allow_cpu in the spec) if a CPU run is what you meant."
        )
    return device


def _hash_outputs(repo: Path) -> dict[str, str]:
    """sha256 every mp4/png under the repository's output directories.

    Free parity check: two arms of an A/B that is supposed to be byte-identical
    should print the same digests, which confirms it without downloading a
    single file off the box.
    """
    digests: dict[str, str] = {}
    # Only the output directories a run writes into. `tests/` is deliberately
    # excluded: its expected-output trees hold hundreds of committed frames
    # that no step produced, and hashing them says nothing while costing
    # seconds and drowning the ones that matter.
    for root in ("algan_outputs", "benchmarks/algan_outputs"):
        base = repo / root
        if not base.is_dir():
            continue
        for path in sorted(base.rglob("*")):
            if path.suffix.lower() not in (".mp4", ".png") or not path.is_file():
                continue
            digest = hashlib.sha256(path.read_bytes()).hexdigest()
            digests[str(path.relative_to(repo))] = digest[:16]
    return digests


def run_step(
    name: str,
    command: str,
    repo: Path,
    out_dir: Path,
    env: dict[str, str],
    timeout: float | None,
) -> dict:
    """Run one step, streaming its output to stdout and to its own log file."""
    _banner(f"=== STEP {name} ===")
    _log(f"$ {command}")
    for key in sorted(env):
        _log(f"  env {key}={env[key]}")

    log_path = out_dir / f"{name}.log"
    started = time.time()
    with log_path.open("w", encoding="utf-8", errors="replace") as log_file:
        process = subprocess.Popen(
            command,
            shell=True,
            cwd=repo,
            env={**os.environ, **env},
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            text=True,
            errors="replace",
            bufsize=1,
        )
        try:
            assert process.stdout is not None
            for line in process.stdout:
                sys.stdout.write(line)
                sys.stdout.flush()
                log_file.write(line)
            returncode = process.wait(timeout=timeout)
        except subprocess.TimeoutExpired:
            process.kill()
            process.wait()
            returncode = -9
            _log(f"!! step {name} exceeded its {timeout}s timeout and was killed")
    seconds = time.time() - started

    status = "ok" if returncode == 0 else "failed"
    _log(f"--- step {name}: {status} (rc={returncode}) in {seconds:.1f}s")
    return {
        "name": name,
        "command": command,
        "env": env,
        "status": status,
        "returncode": returncode,
        "seconds": round(seconds, 2),
        "log": str(log_path),
    }


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--spec",
        required=True,
        help="the run spec as JSON, or @<path> to read it from a file",
    )
    parser.add_argument("--work-dir", default="/kaggle/working")
    parser.add_argument("--repo", default=None, help="defaults to <work-dir>/algan")
    parser.add_argument(
        "--allow-cpu",
        action="store_true",
        help="do not abort when Algan resolves a non-CUDA render device",
    )
    args = parser.parse_args(argv)

    raw = args.spec
    if raw.startswith("@"):
        raw = Path(raw[1:]).read_text(encoding="utf-8")
    spec = json.loads(raw)

    work = Path(args.work_dir)
    repo = Path(args.repo) if args.repo else work / "algan"
    tag = spec.get("tag", "run")
    out_dir = work / "out" / tag
    out_dir.mkdir(parents=True, exist_ok=True)
    results_path = out_dir / "results.json"

    allow_cpu = args.allow_cpu or bool(spec.get("allow_cpu"))
    force = bool(spec.get("force"))
    base_env = {str(k): str(v) for k, v in (spec.get("env") or {}).items()}
    timeout = spec.get("step_timeout_seconds")

    _banner(f"algan Kaggle harness -- tag {tag}")
    _log(f"repo      {repo}")
    _log(f"branch    {spec.get('branch')}")
    _log(f"commit    {spec.get('commit', '(resolved on the box)')}")
    _log(f"steps     {[s['name'] for s in spec['steps']]}")

    device = check_render_device(repo, allow_cpu)
    _log(f"render device: {device}")

    # Resume: a step that already exited 0 in a previous session of this tag is
    # skipped, so a run cut short by the session timeout is continued by
    # re-saving the same notebook rather than redone from the top.
    previous: dict[str, dict] = {}
    if results_path.exists() and not force:
        try:
            prior = json.loads(results_path.read_text(encoding="utf-8"))
            previous = {
                s["name"]: s for s in prior.get("steps", []) if s.get("status") == "ok"
            }
        except (ValueError, KeyError):
            previous = {}
        if previous:
            _log(f"resuming: already complete {sorted(previous)}")

    steps: list[dict] = []
    for step in spec["steps"]:
        name = step["name"]
        if name in previous:
            _log(
                f"=== STEP {name} === skipped (already succeeded in an earlier session)"
            )
            steps.append({**previous[name], "skipped": True})
            continue
        env = {
            **base_env,
            **{str(k): str(v) for k, v in (step.get("env") or {}).items()},
        }
        steps.append(run_step(name, step["command"], repo, out_dir, env, timeout))
        # Written after every step, so a session killed by the timeout still
        # leaves a resume point and the results of what did finish.
        results_path.write_text(
            json.dumps({"tag": tag, "device": device, "steps": steps}, indent=2),
            encoding="utf-8",
        )

    commit = subprocess.run(
        ["git", "rev-parse", "HEAD"], cwd=repo, capture_output=True, text=True
    ).stdout.strip()
    summary = {
        "tag": tag,
        "device": device,
        "branch": spec.get("branch"),
        "commit": commit,
        "steps": steps,
        "sha256": _hash_outputs(repo),
    }
    results_path.write_text(json.dumps(summary, indent=2), encoding="utf-8")

    _banner("summary")
    for step in steps:
        mark = "SKIP" if step.get("skipped") else step["status"].upper()
        _log(f"{mark:>6}  {step['seconds']:>8.1f}s  {step['name']}")
    for path, digest in summary["sha256"].items():
        _log(f"sha256  {digest}  {path}")

    # The one line everything downstream greps for.
    _log(RESULTS_PREFIX + json.dumps(summary, separators=(",", ":")))

    failed = [s["name"] for s in steps if s["status"] != "ok"]
    if failed:
        _log(f"FAILED steps: {failed}")
        return 1
    _log("ALL STEPS OK")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
