from algan.constants.color import *


#DEFAULT_SPRITE_COLOR = BLACK
DEFAULT_BACKGROUND_COLOR = WHITE.mult_rgb(0.12)
DEFAULT_FRAME = DEFAULT_BACKGROUND_COLOR

DEFAULT_TEXT_COLOR = WHITE# + GLOW * 0.05# * 0.9

DEFAULT_BUFFER = 0.1
