name: Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install system dependencies for manimpango
        run: |
          sudo apt-get update
          sudo apt-get install -y libpango1.0-dev libcairo2-dev pkg-config

      - name: Install uv
        uses: ./.github/actions/install-uv

      - name: Create venv
        run: uv venv
        shell: bash

      - name: Install repo and dev dependencies
        uses: ./.github/actions/install-deps

      - name: Run tests
        run: |
              uvx pytest 

      # - name: Upload coverage to Codecov
      #   uses: codecov/codecov-action@v5

      # - name: Upload test results to Codecov
      #   if: ${{ !cancelled() }}
      #   uses: codecov/test-results-action@v1
