name: Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install algan and its dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e .[dev]
      
      # For debugging purposes
      - name: Check Python version
        run: python3 --version

      - name: Check installed packages
        run: pip list
      
      - name: Test with pytest and generate coverage report
        run: |
          python3 -m pytest -n 2 --dist=loadgroup --cov=deepinv --junitxml=junit.xml -o junit_family=legacy -v
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5

      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/test-results-action@v1